
# Set the base image
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Set the working directory
WORKDIR /app

# Copy the project file and restore dependencies
COPY pest.tracking.csproj .
RUN dotnet restore

# Copy the source code
COPY . .

# Build the application
RUN dotnet publish -c Release -o out

# Set the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

# Set the working directory
WORKDIR /app
EXPOSE 8080

# Copy the published output from the build stage
COPY --from=build /app/out .

# Set the entry point
ENTRYPOINT ["dotnet", "pest.tracking.dll"]