services:
  tracking:
    container_name: tracking
    build:
      context: ./src/pest.tracking
      dockerfile: dockerfile
    ports:
      - 8080:8080
    networks:
      - ui
  tracking-persistency:
    container_name: tracking-persistency
    image: mongo:latest
    volumes:
      - tracking-persistency:/data/db
      - tracking-persistency:/data/configdb
    ports:
      - 27017:27017
    networks: 
      - ui

  pricing:
    container_name: pricing
    build:
      context: ./src/pest.pricing
      dockerfile: dockerfile
    ports:
      - 8090:8080
    networks:
      - ui

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
      
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  pest:
    driver: bridge
  ui:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.0.0/24"

volumes:
  tracking-persistency:
    driver: local  