version: '3'
services:
  pest-tracking:
    container_name: tracking
    build:
      context: ./src/pest.tracking
      dockerfile: dockerfile
    ports:
      - 8080:8080

  pest-pricing:
    container_name: pricing
    build:
      context: ./src/pest.pricing
      dockerfile: dockerfile
    ports:
      - 8090:8080