services:

# pest unique identifier service
  puid:
      container_name: piud
      build:
        context: ./src/pest.puid
        dockerfile: dockerfile
      ports:
        - 8010:8080
      networks:
        - ui

# parcel service
  parcel:
    container_name: parcel
    build:
      context: ./src/pest.parcel
      dockerfile: dockerfile
    ports:
      - 8003:8080
    networks:
      - ui
      - infrastructure
        
# tracking service
  tracking:
    container_name: tracking
    build:
      context: ./src/pest.tracking
      dockerfile: dockerfile
    ports:
      - 8001:8080
    networks:
      - ui
  tracking-persistency:
    container_name: tracking-persistency
    image: mongo:latest
    volumes:
      - tracking-persistency:/data/db
      - tracking-persistency:/data/configdb
    ports:
      - 27017:27017
    networks: 
      - ui

# pricing service
  pricing:
    container_name: pricing
    build:
      context: ./src/pest.pricing
      dockerfile: dockerfile
    ports:
      - 8002:8080
    networks:
      - ui

# infrastructure
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - infrastructure
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    networks:
      - infrastructure
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    networks:
      - infrastructure
    environment:
      POSTGRES_USER: pest
      POSTGRES_PASSWORD: pest      
      PGHOST: postgres

# tools
  kafka-manager:
    container_name: kafka-manager
    image: kafkamanager/kafka-manager
    ports:
      - '8011:9000'
    depends_on:
      - zookeeper
    environment:
      ZK_HOSTS: zookeeper:2181
    networks:
      - tools
      - infrastructure

  kafka-magic:
    container_name: kafka-magic
    image: digitsy/kafka-magic
    ports:
      - '8012:80'
    depends_on:
      - zookeeper
    networks:
      - tools
      - infrastructure

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8013:8080
    environment:
        DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - tools
      - infrastructure

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8014:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pest@pest.com
      PGADMIN_DEFAULT_PASSWORD: pest
    networks:
      - tools
      - infrastructure
      
networks:
  pest:
    driver: bridge
  ui:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.0.0/24"
  tools:
    driver: bridge
    ipam:
      config:
        - subnet: "10.20.0.0/24"
  infrastructure:
    driver: bridge
    ipam:
      config:
        - subnet: "10.100.0.0/24"
volumes:
  tracking-persistency:
    driver: local