version: '3'
services:
  pest-tracking:
    container_name: tracking
    build:
      context: ./src/pest.tracking
      dockerfile: dockerfile
    ports:
      - 8080:8080
    networks:
      - ui

  pest-pricing:
    container_name: pricing
    build:
      context: ./src/pest.pricing
      dockerfile: dockerfile
    ports:
      - 8090:8080
    networks:
      - ui

networks:
  pest:
    driver: bridge
  ui:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.0.0/24"