 @TRACKING_PORT=8001
@PRICING_PORT=8002

### smoke test TRACKING
GET http://localhost:{{TRACKING_PORT}}/weatherforecast
Content-Type: application/json

### smoke test PRICING 
GET http://localhost:{{PRICING_PORT}}/weatherforecast
Content-Type: application/json




________________________________________________


### put new parel

### get parcel tracking

### get parcel pricing

### contenerize

### decontenerize

